### ISSUE TITLE
Any future plans to make an stl for the airpods pro case?

### ISSUE THREAD

**Issue by printd3v** [kenp-io/not-for-airpods-repairs#3]
Just repaired my airpods pro, had to sacrifice the wireless charger but it does still work... can't seem to find a shell stl for it and I can't really design it since I've trashed the case.

**Comment by krupal157** [comment]
I have the case if you want but it has some texture on it, i can send you a link if you want to buy it.
i made mine in solid (925) silver.
![E1AAC556-F4E7-44E8-9C46-49EF28B451B8](https://user-images.githubusercontent.com/60811015/195137994-83d930a5-3956-4348-9f82-603a90aa51f9.jpeg)
![6535DD0B-FACA-4301-B663-6E208C05435C](https://user-images.githubusercontent.com/60811015/195138001-2ef838f8-68cc-4e93-a7ce-517ba3456ea1.jpeg)

![54F2803F-9742-4185-B467-8611FA357443](https://user-images.githubusercontent.com/60811015/195137971-682c472a-30b4-4d21-9822-ba12a94de4e4.jpeg)

**Comment by kenp-io** [comment]
@printd3v Yes, they are coming! Will be released at the same time as USB-C replacement part.
@krupal157 Looks cool. Surely you can roll back the CAD file before texture was added? You can make a pull request and share it, I'm sure people will appreciate it.

**Comment by MrFrio** [comment]
So can the pros be taken out the same way the 1st and 2nd gen AirPods can?
